### ISSUE TITLE
What does FTD stand for?

### ISSUE THREAD

**Issue by JulianKnodt** [omerbt/MultiDiffusion#22]
In the paper, the abbreviation FTD is used to represent the loss of multi diffusion as compared to standard diffusion. It's never explicitly mentioned what this abbreviation stands for, so I was hoping that could be clarified.

**Comment by omerbt** [comment]
Hi, FTD stands for _Follow The Diffusion_. The MultiDiffusion process aims to 'follows the diffusion paths', in the sense that finds a solution that is as close as possible to each denoising suggestion.
